[ACEM] llteacher x ruff
Policy: Ruff 0.14.8
Fixed: 1 violations

Original Violations:

src/courses/tests/test_views.py:
F811 [*] Redefinition of unused `HomeworkProgressWidget` from line 1079
    --> src/courses/tests/test_views.py:1118:48
     |
1116 |         self.assertEqual(response.status_code, 302)
1117 |
1118 |         from homeworks.models import Homework, HomeworkProgressWidget
     |                                                ^^^^^^^^^^^^^^^^^^^^^^ `HomeworkProgressWidget` redefined here
1119 |
1120 |         homework = Homework.objects.get(title="Homework With Widgets")
     |
    ::: src/courses/tests/test_views.py:1079:38
     |
1077 |         from django.utils import timezone
1078 |         from datetime import timedelta
1079 |         from homeworks.models import HomeworkProgressWidget
     |                                      ---------------------- previous definition of `HomeworkProgressWidget` here
1080 |
1081 |         due_date = timezone.now() + timedelta(days=7)
     |
help: Remove definition: `HomeworkProgressWidget`

Found 1 error.
[*] 1 fixable with the `--fix` option.

Automated by ACEM - Initiative #25